config:
  max_old: 5  # Number of old sqlite databases to keep
  pause: 1.1  # Decimal seconds to pause
  pause_rate: 0  # Percentage of requests that should pause before returning
  error_rate: 0  # Percentage of requests that should return 400 response
  sample_rate: 0  # Percentage of requests that should be saved to sqlite db
