phases:
  build:
    - docker:
        args:
          - build
          - -t
          - closeio/blackholebandicoot:{{ VERSION }}
          - -f Dockerfile
          - ../..

  test:
    - docker:
        ignore_error: true
        args:
          - stop
          - blackhole
    - docker:
        ignore_error: true
        args:
          - rm
          - blackhole
    - docker:
        args:
          - run -p 4000:4000
          - -d
          - --name
          - blackhole
          - closeio/blackholebandicoot:{{ VERSION }}
    - docker:
        args:
          - exec
          - blackhole
          - curl
          - --retry
          - 3
          - --retry-delay
          - 5
          - http://localhost:4000/
  
  push:
    - docker:
        args:
          - tag
          - closeio/blackholebandicoot:{{ VERSION }}
          - closeio/blackholebandicoot:latest
    - docker:
        args:
          - push
          - closeio/blackholebandicoot:{{ VERSION }}
    - docker:
        args:
          - push
          - closeio/blackholebandicoot:latest