version: 2
jobs:
  doit:
    docker:
      - image: python:3.5-jessie
    working_directory: /tmp
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Clone DevOps
          command: git@github.com:closeio/devops.git

      - run:
          name: Build
          command: scripts/k8s-cicd/k8scicd.sh -p build -d blackholebandicoot/services -s

      - run:
          name: Test
          command: scripts/k8s-cicd/k8scicd.sh -p test -d blackholebandicoot/services -s

      - run:
          name: Push
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              scripts/k8s-cicd/k8scicd.sh -p push -d blackholebandicoot/services -s
            fi

workflows:
  version: 2
  workflow:
    jobs:
      - doit
