version: 2
jobs:
  doit:
    docker:
      - image: circleci/python:3.5.4-jessie
    working_directory: /home/circleci/blackholebandicoot
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Clone DevOps
          command: git clone git@github.com:closeio/devops.git /home/circleci/devops

      - run:
          name: Pip DevOps
          command: sudo pip install -r /home/circleci/devops/scripts/k8s-cicd/requirements.txt

      - run:
          name: Build
          command: /home/circleci/devops/scripts/k8s-cicd/k8scicd.sh -p build -d /home/circleci/blackholebandicoot/services -s

      - run:
          name: Test
          command: /home/circleci/devops/scripts/k8s-cicd/k8scicd.sh -p test -d /home/circleci/blackholebandicoot/services -s

      - run:
          name: Push
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              /home/circleci/devops/scripts/k8s-cicd/k8scicd.sh -p push -d /home/circleci/blackholebandicoot/services -s
            fi

workflows:
  version: 2
  workflow:
    jobs:
      - doit
